apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ankra-guestbook-db
  labels:
    app.kubernetes.io/name: ankra-guestbook-db
    app.kubernetes.io/managed-by: ankra
spec:
  instances: ${{ ankra.database_instances }}
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2
  storage:
    size: ${{ ankra.database_storage }}
  bootstrap:
    initdb:
      database: ankra-guestbook-db
      owner: ankra-guestbook-db
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: false
