apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guestbook-flowtest
  labels:
    app.kubernetes.io/name: guestbook-flowtest
  annotations:
    ankra.io/generated: "true"
    cert-manager.io/cluster-issuer: ${{ ankra.ingress_tls_issuer }}
spec:
  ingressClassName: ${{ ankra.ingress_class }}
  tls:
    - hosts:
        - ${{ ankra.ingress_host }}
      secretName: guestbook-flowtest-tls
  rules:
    - host: ${{ ankra.ingress_host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: guestbook-flowtest
                port:
                  number: 80
