apiVersion: v1
kind: Service
metadata:
  name: ankra-guestbook
  labels:
    app.kubernetes.io/name: ankra-guestbook
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ankra-guestbook
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
