apiVersion: v1
kind: Service
metadata:
  name: guestbook-coldwalk
  labels:
    app.kubernetes.io/name: guestbook-coldwalk
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: guestbook-coldwalk
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
